name: Build and deploy
on: [push]
jobs:
  build:
    if: github.ref == 'refs/heads/master'
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: akiko643/discord-contest-bot
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
          docker pull akiko643/discord-contest-bot
          docker rm -f discord-contest-bot || true
          docker run -it -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} --name discord-contest-bot akiko643/discord-contest-bot
